---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.mode }}
  hostPath:
    path: {{ .Values.pv.path | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name }}
spec:
  storageClassName: manual
  accessModes:
    - {{.Values.pvc.mode }}
  resources:
    requests:
      storage: {{.Values.pvc.storage }}
