apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.svc.name }}
  labels:
    name: {{ .Values.web.svc.name }}
    app: {{ .Values.web.svc.app }}
spec:
  selector:
    name: {{ .Values.web.deploy.name }}
  type: NodePort
  ports:
   - port: {{ .Values.web.deploy.port }} 
     nodePort: {{ .Values.web.svc.port }}
     protocol: TCP
