apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  labels:
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.pod.port.port }}
      nodePort: {{ .Values.service.port.port }}
      name: {{ .Values.service.port.name }}
  selector:
    name: {{ .Values.pod.name }}
