apiVersion: batch/v1
kind: Job
metadata:
 name: ignite-activate
 namespace: ignite
 annotations:
   "helm.sh/hook": post-install
   "helm.sh/hook-weight": "-5"
   "helm.sh/hook-delete-policy": hook-succeeded
spec:
 ttlSecondsAfterFinished: 100
 template:
  spec:
    containers:
    - name: ignite
      image: kiranpesarlanka/ignite:v2
      command: [/opt/ignite/apache-ignite-2.8.1-bin/bin/control.sh,   --activate,   --host ignite]
    restartPolicy: Never
