apiVersion: v1
kind: Service
metadata:
  labels:
    app: ignite
  name: ignite
  namespace: ignite

spec:
  clusterIP: None
  ports:
  - port: 47500
  selector:
    app: ignite
---
apiVersion: v1
kind: Service
metadata:
 name: ignite-client
 labels:
   app: ignite
 namespace: ignite
spec:
 selector:
   app: ignite
 type: NodePort
 ports:
  - port: 10800 
    targetPort: 10800 
    protocol: TCP



